#+STARTUP: showall indent

* Windows Utilities

Windows で動作するユティリティコマンド群です。

本コマンドは AutoHotKey_L（v1.1系）のスクリプトとして作成しています。
AutoHotKey については、以下を参照してください。

- https://www.autohotkey.com/
- https://so-zou.jp/software/tool/system/auto-hot-key/introduction/
- http://ahkwiki.net/Top

Unicode 64bit のコンパイラでコンパイルしたバイナリも登録しています。

全てのコマンドは、DrvFs ファイルシステム上のフォルダに格納する必要があります。
WSL からコマンドを利用する場合には、格納したフォルダもしくはそのフォルダへのシンボリックリンクに
コマンドパスを通してお使いください。

** ■ wslemacs-start

WSL emacs をデーモンモードで起動するためのコマンドです。以降に紹介している wslclient を利用する
ために作成しました。

Startup フォルダに格納するか、ショートカットを格納してご利用ください。

*** 使用方法

#+BEGIN_EXAMPLE
wslemacs-start.exe
#+END_EXAMPLE

wslemacs-start.ahk を見ていただくと分かる通り、emacs はログインシェルかつインタラクティブ
モードで起動した bash から起動するようにしています。これは、環境変数などが極力設定された
状態で emacs を立ち上げるようにするためです。bash 起動時にインタラクティブな応答（例えば、
keychain のパスフレーズの入力など）があるとコマンドが正常に起動できませんので、ご留意ください。
そのような応答が必要な場合は、OS 起動後一回のみ、WSL のコンソールを立ち上げ、emacs --daemon
コマンドを使って起動するようにしてください。

** ■ wslemacs-stop

WSL emacs を終了するためのコマンドです。

*** 使用方法

#+BEGIN_EXAMPLE
wslemacs-stop.exe
#+END_EXAMPLE

** ■ wslclient

VcXsrv X サーバで動作している Windows Subsystem for Linux の emacs と連携可能な emacsclient コマンドです。

emacs を開いている X サーバの画面をアクティベートする機能をサポートしています。

emacs は事前にデーモンモードで起動しておくか、普通に emacs を立ち上げておいてください。

*** 使用方法

#+BEGIN_EXAMPLE
wslclient.exe filename
#+END_EXAMPLE

コマンドの中で wsl.exe を使っています。複数の Linux のディストリビューションをインストールしている場合は、
wslconfig /s コマンドで連携する（emacsclient をコールする）ディストリビューションを指定してください。

emacs や Windows 側に必要となる設定は、以下の説明を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/75.html][WSL の emacsclient を Windows から利用するための設定]]

** ■ winactivate

開いているウィンドウをアクティベートするためのコマンドです。

Cygwin もしくは WSL の sglstart コマンドから利用することを目的として作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
winactivate.exe filename
#+END_EXAMPLE

*** 使用例

#+BEGIN_EXAMPLE
winactivate.exe foo.txt
#+END_EXAMPLE

この場合、以下の正規表現にマッチするタイトルを持つアクティブではないウィンドウがあれば、
アクティベートされます。

#+BEGIN_EXAMPLE
(^| )(foo\.txt|foo)( |$)
#+END_EXAMPLE

該当するウィンドウがあった場合は 0 を、なかった場合は 1 を返します。

*** その他

sglstart コマンドについては、以下を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/60.html][singleton な動きをする cygstart 的コマンドを使うための設定 （Cygwin版）]]
- [[https://www49.atwiki.jp/ntemacs/pages/63.html][singleton な動きをする cygstart 的コマンドを使うための設定 （WSL版）]]
