#+STARTUP: showall indent

* Windows Utilities

Windows で動作するユティリティコマンド群です。

本コマンドは AutoHotKey_L（v1.1系）のスクリプトとして作成しています。
AutoHotKey については、以下を参照してください。

- https://www.autohotkey.com/
- https://so-zou.jp/software/tool/system/auto-hot-key/introduction/
- http://ahkwiki.net/Top

Unicode 64bit のコンパイラでコンパイルしたバイナリも登録しています。

全てのコマンドは、DrvFs ファイルシステム上のフォルダに格納する必要があります。
WSL からコマンドを利用する場合には、格納したフォルダもしくはそのフォルダへのシンボリックリンクに
コマンドパスを通してお使いください。

コマンドの中で wsl.exe を使っています。複数の Linux のディストリビューションをインストールしている場合は、
wslconfig /s コマンドで連携する（emacsclient をコールする）ディストリビューションを指定してください。

** ■ wslemacs-start

WSL Emacs をデーモンモードで起動するためのコマンドです。以降に紹介している wslclient を利用する
ために作成しました。

Startup フォルダに格納するか、ショートカットを格納してご利用ください。

*** 使用方法

#+BEGIN_EXAMPLE
wslemacs-start.exe
#+END_EXAMPLE

wslemacs-start.ahk を見ていただくと分かる通り、Emacs はログインシェルかつインタラクティブ
モードで起動した bash から起動するようにしています。これは、環境変数などが極力設定された
状態で Emacs が立ち上がるようにするためです。bash 起動時にインタラクティブな応答（例えば、
keychain や ssh-add 実行時のパスフレーズの入力など）があるとコマンドが正常に起動できません
ので、ご留意ください。
そのような応答が必要な場合は、WSL のコンソールを立ち上げた後、emacs --daemon コマンドを使って
Emacs を起動するようにしてください。

なお、パスフレーズの入力を回避する方法としては、ssh-agent-wsl を使う方法があるようです。
詳しくは、以下のサイトを参照してください。

- https://laboradian.com/use-ssh-agent-wsl/

** ■ wslemacs-stop

WSL Emacs を終了するためのコマンドです。

*** 使用方法

#+BEGIN_EXAMPLE
wslemacs-stop.exe
#+END_EXAMPLE

** ■ wslclient / emacsclientw

WSL Emacs と連携可能な emacsclient コマンドです。

Emacs は事前にデーモンモードで起動しておくか、普通に Emacs を立ち上げておいてください。

また、Xサーバとして VcXsrv が起動している必要があります。

*** 使用方法

#+BEGIN_EXAMPLE
wslclient.exe [options] file...               # no-wait version for Windows
wslclient-w.exe [options] file...             # wait version for Windows
emacsclientw.exe [options] file...            # emacsclient command with activate control
emacsclientw [-n] [-c] [+line:column] file... # for WSL
#+END_EXAMPLE

Emacs や Windows 側に必要となる設定は、以下の説明を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/75.html][WSL の emacsclient を Windows から利用するための設定]]

wslemacs-start.exe で Emacs を起動している場合は、Alt+e で本コマンドを起動することもできます。
（wslclient.exe、emacsclientw.exe は、wslemacs-start.exe と 同じフォルダに格納しておく
必要があります。）

wslclient.exe は既に Emacs のフレームがあれば、そのフレーム上に表示する仕様としています。
また、wslclient-w.exe は常に新しいフレームを作って表示する仕様としています。

*** 注意事項

**** ● exe コマンド初回実行について

exe コマンドを新規にインストールした場合、もしくは更新した場合には、一回目のコマンド
実行時に正常に動作しないこと（新規にフレームが開くなど）があるようです。
二回目からは正常に動作します。

**** ● ダブルコーテーション、シングルコーテーションを含むファイルについて

ダブルコーテーション、シングルコーテーションを含むファイルは、正常にハンドリング
できません。制約事項とさせてください。

** ■ winactivate

開いているウィンドウをアクティベートするためのコマンドです。

Cygwin もしくは WSL の sglstart コマンドから利用することを目的として作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
winactivate.exe filename
#+END_EXAMPLE

*** 使用例

#+BEGIN_EXAMPLE
winactivate.exe foo.txt
#+END_EXAMPLE

この場合、以下の正規表現にマッチするタイトルを持つアクティブではないウィンドウがあれば、
アクティベートされます。

#+BEGIN_EXAMPLE
(^| )(foo\.txt|foo)( |$)
#+END_EXAMPLE

該当するウィンドウがあった場合は 0 を、なかった場合は 1 を返します。

*** その他

sglstart コマンドについては、以下を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/60.html][singleton な動きをする cygstart 的コマンドを使うための設定 （Cygwin版）]]
- [[https://www49.atwiki.jp/ntemacs/pages/63.html][singleton な動きをする cygstart 的コマンドを使うための設定 （WSL版）]]
