#+STARTUP: showall indent

* Windows Utilities

Windows で動作するユティリティコマンド群です。

** ■ wslclient

VcXsrv X サーバで動作している Windows Subsystem for Linux の emacs と連携可能な emacsclient コマンドです。

WSL の emacsclient を起動する他、emacs を開いている X サーバの画面をアクティベートする機能をサポートしています。

*** 使用方法

wslclient.exe filename

コマンドの中で wsl.exe を使っています。複数の Linux のディストリビューションをインストールしている場合は、
wslconfig /s コマンドで連携する（emacsclient をコールする）ディストリビューションを指定してください。

emacs 側に必要となる設定は、以下の 21）の説明を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/69.html][WSL で emacs を使うための設定]]

*** その他

AutoHotKey_L のスクリプトとして作成しています。Unicode 64bit のコンパイラでコンパイルしたバイナリも登録しています。

AutoHotKey については、以下を参照してください。

- https://so-zou.jp/software/tool/system/auto-hot-key/introduction/
- http://ahkwiki.net/Top

** ■ winactivate

開いているウィンドウをアクティベートするためのコマンドです。

Cygwin もしくは WSL の sglstart コマンドから利用することを目的として作成しました。
sglstart コマンドと同じディレクトリに格納してお使いください。

*** 使用方法

winactivate.exe filename

*** 使用例

winactivate.exe foo.txt

この場合、以下の正規表現にマッチするタイトルを持つウィンドウがあれば、アクティベートされます。

#+BEGIN_EXAMPLE
(^| )(foo\.txt|foo)( |$)
#+END_EXAMPLE

該当するウィンドウがあった場合は 0 を、なかった場合は 1 を返します。

*** その他

AutoHotKey_L のスクリプトとして作成しています。Unicode 64bit のコンパイラでコンパイルしたバイナリも登録しています。

sglstart コマンドについては、以下を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/60.html][singleton な動きをする cygstart 的コマンドを使うための設定 （Cygwin版）]]
- [[https://www49.atwiki.jp/ntemacs/pages/63.html][singleton な動きをする cygstart 的コマンドを使うための設定 （WSL版）]]
