#+STARTUP: showall indent

* Windows Utilities

Windows で動作するユティリティコマンド群です。
全てのコマンドは、DrvFs ファイルシステム上のフォルダに格納する必要があります。
WSL からコマンドを利用する場合には、格納したフォルダもしくはそのフォルダへのシンボリックリンクに
コマンドパスを通してお使いください。

** ■ wslclient

VcXsrv X サーバで動作している Windows Subsystem for Linux の emacs と連携可能な emacsclient コマンドです。

WSL の emacsclient を起動する他、emacs を開いている X サーバの画面をアクティベートする機能をサポートしています。

emacs は事前にデーモンモード（emacs --daemon）で起動しておくか、普通に emacs を立ち上げておいてください。

*** 使用方法

#+BEGIN_EXAMPLE
wslclient.exe filename
#+END_EXAMPLE

コマンドの中で wsl.exe を使っています。複数の Linux のディストリビューションをインストールしている場合は、
wslconfig /s コマンドで連携する（emacsclient をコールする）ディストリビューションを指定してください。
Windows 10 1709 より前のバージョンで WSL を利用している場合は、wslclient.ahk のコメントを参考として
必要な行を有効にし、再コンパイルしてご利用ください。

emacs 側に必要となる設定は、以下の説明を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/75.html][WSL の emacsclient を Windows から利用するための設定]]

*** その他

AutoHotKey_L（v1.1系）のスクリプトとして作成しています。Unicode 64bit のコンパイラでコンパイルしたバイナリも登録しています。

AutoHotKey については、以下を参照してください。

- https://www.autohotkey.com/
- https://so-zou.jp/software/tool/system/auto-hot-key/introduction/
- http://ahkwiki.net/Top

** ■ winactivate

開いているウィンドウをアクティベートするためのコマンドです。

Cygwin もしくは WSL の sglstart コマンドから利用することを目的として作成しました。

*** 使用方法

#+BEGIN_EXAMPLE
winactivate.exe filename
#+END_EXAMPLE

*** 使用例

#+BEGIN_EXAMPLE
winactivate.exe foo.txt
#+END_EXAMPLE

この場合、以下の正規表現にマッチするタイトルを持つアクティブではないウィンドウがあれば、
アクティベートされます。

#+BEGIN_EXAMPLE
(^| )(foo\.txt|foo)( |$)
#+END_EXAMPLE

該当するウィンドウがあった場合は 0 を、なかった場合は 1 を返します。

*** その他

AutoHotKey のスクリプトとして作成しています。Unicode 64bit のコンパイラでコンパイルした
バイナリも登録しています。

sglstart コマンドについては、以下を参照してください。

- [[https://www49.atwiki.jp/ntemacs/pages/60.html][singleton な動きをする cygstart 的コマンドを使うための設定 （Cygwin版）]]
- [[https://www49.atwiki.jp/ntemacs/pages/63.html][singleton な動きをする cygstart 的コマンドを使うための設定 （WSL版）]]
