#!/bin/bash
# -*- mode: sh; coding: utf-8-unix -*-

for arg; do
    args+=("$(readlink -m -- "$arg")")
done
set -- "${args[@]}"

cd

export EMACSCLIENTW_PID=$$
WSLENV=EMACSCLIENTW_PID
emacsclientw.exe "$@"
